# Red Hat Universal Base Image 10
FROM registry.access.redhat.com/ubi10/ubi

# Enable required repositories
RUN dnf install -y 'dnf-command(config-manager)' && \
    dnf config-manager --enable ubi-10-codeready-builder-rpms && \
    dnf install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-10.noarch.rpm

# Core build tools
RUN dnf install -y \
        make ninja-build cmake ccache git git-lfs \
        python3 python3-pip wget zip unzip rsync \
        openssh-clients file

# GCC 14 (system) + GCC 15 (toolset)
RUN dnf install -y gcc gcc-c++ gdb \
        gcc-toolset-15-gcc gcc-toolset-15-gcc-c++ gcc-toolset-15-binutils

# LLVM / Clang
RUN dnf install -y \
        llvm-toolset clang clang-tools-extra clang-devel llvm-devel lld lldb

# Static analysis and documentation
RUN dnf install -y cppcheck doxygen graphviz

# Editors
RUN dnf install -y neovim nano

# Python packages
RUN python3 -m pip install --upgrade pip setuptools && \
    python3 -m pip install conan && \
    conan --version

# Conan configuration for containers
ENV CONAN_SYSREQUIRES_SUDO=0 \
    CONAN_SYSREQUIRES_MODE=enabled

# include-what-you-use (build from source)
ARG IWYU_BRANCH="clang_19"
ENV IWYU=/home/iwyu \
    IWYU_BUILD=/home/iwyu/build \
    IWYU_SRC=/home/iwyu/include-what-you-use

RUN mkdir -p ${IWYU_BUILD} && \
    git clone --branch ${IWYU_BRANCH} --depth 1 \
        https://github.com/include-what-you-use/include-what-you-use.git \
        ${IWYU_SRC}

RUN cmake -S ${IWYU_SRC} -B ${IWYU_BUILD} -G "Unix Makefiles" \
        -DCMAKE_PREFIX_PATH=$(llvm-config --prefix) && \
    cmake --build ${IWYU_BUILD} -j && \
    cmake --install ${IWYU_BUILD}

# Link Clang resource headers so IWYU can find them
RUN mkdir -p $(include-what-you-use -print-resource-dir 2>/dev/null) && \
    ln -sf $(clang -print-resource-dir)/include \
        $(include-what-you-use -print-resource-dir 2>/dev/null)/include

# Cleanup
RUN dnf clean all && rm -rf /var/cache/dnf

# Allow the user to set compiler defaults
ARG USE_CLANG
# if --build-arg USE_CLANG=1, set CC to 'clang' or set to null otherwise.
ENV CC=${USE_CLANG:+"clang"}
ENV CXX=${USE_CLANG:+"clang++"}
# if CC is null, set it to 'gcc' (or leave as is otherwise).
ENV CC=${CC:-"gcc"}
ENV CXX=${CXX:-"g++"}

CMD ["/bin/bash"]
